DROP DATABASE IF EXISTS openport_database;

CREATE DATABASE IF NOT EXISTS openport_database;

USE openport_database;

CREATE TABLE IF NOT EXISTS Country (
  CountryID int AUTO_INCREMENT PRIMARY KEY,
  CountryName VARCHAR(50)
);

INSERT INTO Country(CountryName) VALUES ('Afghanistan');
INSERT INTO Country(CountryName) VALUES ('Albania');
INSERT INTO Country(CountryName) VALUES ('Algeria');
INSERT INTO Country(CountryName) VALUES ('American Samoa');
INSERT INTO Country(CountryName) VALUES ('Andorra');
INSERT INTO Country(CountryName) VALUES ('Angola');
INSERT INTO Country(CountryName) VALUES ('Antigua and Barbuda');
INSERT INTO Country(CountryName) VALUES ('Argentina');
INSERT INTO Country(CountryName) VALUES ('Armenia');
INSERT INTO Country(CountryName) VALUES ('Aruba');
INSERT INTO Country(CountryName) VALUES ('Australia');
INSERT INTO Country(CountryName) VALUES ('Austria');
INSERT INTO Country(CountryName) VALUES ('Azerbaijan');
INSERT INTO Country(CountryName) VALUES ('The Bahamas');
INSERT INTO Country(CountryName) VALUES ('Bahrain');
INSERT INTO Country(CountryName) VALUES ('Bangladesh');
INSERT INTO Country(CountryName) VALUES ('Barbados');
INSERT INTO Country(CountryName) VALUES ('Belarus');
INSERT INTO Country(CountryName) VALUES ('Belgium');
INSERT INTO Country(CountryName) VALUES ('Belize');
INSERT INTO Country(CountryName) VALUES ('Benin');
INSERT INTO Country(CountryName) VALUES ('Bermuda');
INSERT INTO Country(CountryName) VALUES ('Bhutan');
INSERT INTO Country(CountryName) VALUES ('Bolivia');
INSERT INTO Country(CountryName) VALUES ('Bosnia and Herzegovina');
INSERT INTO Country(CountryName) VALUES ('Botswana');
INSERT INTO Country(CountryName) VALUES ('Brazil');
INSERT INTO Country(CountryName) VALUES ('Brunei');
INSERT INTO Country(CountryName) VALUES ('Bulgaria');
INSERT INTO Country(CountryName) VALUES ('Burkina Faso');
INSERT INTO Country(CountryName) VALUES ('Burundi');
INSERT INTO Country(CountryName) VALUES ('Cabo Verde (Cape Verde)');
INSERT INTO Country(CountryName) VALUES ('Cambodia');
INSERT INTO Country(CountryName) VALUES ('Cameroon');
INSERT INTO Country(CountryName) VALUES ('Canada');
INSERT INTO Country(CountryName) VALUES ('Cayman Islands');
INSERT INTO Country(CountryName) VALUES ('Central African Republic');
INSERT INTO Country(CountryName) VALUES ('Chad');
INSERT INTO Country(CountryName) VALUES ('Chile');
INSERT INTO Country(CountryName) VALUES ('China');
INSERT INTO Country(CountryName) VALUES ('Colombia');
INSERT INTO Country(CountryName) VALUES ('Comoros');
INSERT INTO Country(CountryName) VALUES ('Democratic Republic of the Congo');
INSERT INTO Country(CountryName) VALUES ('Republic of the Congo');
INSERT INTO Country(CountryName) VALUES ('Costa Rica');
INSERT INTO Country(CountryName) VALUES ('Côte d’Ivoire');
INSERT INTO Country(CountryName) VALUES ('Croatia');
INSERT INTO Country(CountryName) VALUES ('Cuba');
INSERT INTO Country(CountryName) VALUES ('Curaçao');
INSERT INTO Country(CountryName) VALUES ('Cyprus');
INSERT INTO Country(CountryName) VALUES ('Czech Republic');
INSERT INTO Country(CountryName) VALUES ('Denmark');
INSERT INTO Country(CountryName) VALUES ('Djibouti');
INSERT INTO Country(CountryName) VALUES ('Dominica');
INSERT INTO Country(CountryName) VALUES ('Dominican Republic');
INSERT INTO Country(CountryName) VALUES ('East Timor (Timor-Leste)');
INSERT INTO Country(CountryName) VALUES ('Ecuador');
INSERT INTO Country(CountryName) VALUES ('Egypt');
INSERT INTO Country(CountryName) VALUES ('El Salvador');
INSERT INTO Country(CountryName) VALUES ('Equatorial Guinea');
INSERT INTO Country(CountryName) VALUES ('Eritrea');
INSERT INTO Country(CountryName) VALUES ('Estonia');
INSERT INTO Country(CountryName) VALUES ('Eswatini (Swaziland)');
INSERT INTO Country(CountryName) VALUES ('Ethiopia');
INSERT INTO Country(CountryName) VALUES ('Faroe Islands');
INSERT INTO Country(CountryName) VALUES ('Fiji');
INSERT INTO Country(CountryName) VALUES ('Finland');
INSERT INTO Country(CountryName) VALUES ('France');
INSERT INTO Country(CountryName) VALUES ('French Guiana');
INSERT INTO Country(CountryName) VALUES ('French Polynesia');
INSERT INTO Country(CountryName) VALUES ('Gabon');
INSERT INTO Country(CountryName) VALUES ('The Gambia');
INSERT INTO Country(CountryName) VALUES ('Gaza Strip');
INSERT INTO Country(CountryName) VALUES ('Georgia');
INSERT INTO Country(CountryName) VALUES ('Germany');
INSERT INTO Country(CountryName) VALUES ('Ghana');
INSERT INTO Country(CountryName) VALUES ('Greece');
INSERT INTO Country(CountryName) VALUES ('Greenland');
INSERT INTO Country(CountryName) VALUES ('Grenada');
INSERT INTO Country(CountryName) VALUES ('Guadeloupe');
INSERT INTO Country(CountryName) VALUES ('Guam');
INSERT INTO Country(CountryName) VALUES ('Guatemala');
INSERT INTO Country(CountryName) VALUES ('Guernsey');
INSERT INTO Country(CountryName) VALUES ('Guinea');
INSERT INTO Country(CountryName) VALUES ('Guinea-Bissau');
INSERT INTO Country(CountryName) VALUES ('Guyana');
INSERT INTO Country(CountryName) VALUES ('Haiti');
INSERT INTO Country(CountryName) VALUES ('Honduras');
INSERT INTO Country(CountryName) VALUES ('Hong Kong');
INSERT INTO Country(CountryName) VALUES ('Hungary');
INSERT INTO Country(CountryName) VALUES ('Iceland');
INSERT INTO Country(CountryName) VALUES ('India');
INSERT INTO Country(CountryName) VALUES ('Indonesia');
INSERT INTO Country(CountryName) VALUES ('Iran');
INSERT INTO Country(CountryName) VALUES ('Iraq');
INSERT INTO Country(CountryName) VALUES ('Ireland');
INSERT INTO Country(CountryName) VALUES ('Isle of Man');
INSERT INTO Country(CountryName) VALUES ('Israel');
INSERT INTO Country(CountryName) VALUES ('Italy');
INSERT INTO Country(CountryName) VALUES ('Jamaica');
INSERT INTO Country(CountryName) VALUES ('Japan');
INSERT INTO Country(CountryName) VALUES ('Jersey');
INSERT INTO Country(CountryName) VALUES ('Jordan');
INSERT INTO Country(CountryName) VALUES ('Kazakhstan');
INSERT INTO Country(CountryName) VALUES ('Kenya');
INSERT INTO Country(CountryName) VALUES ('Kiribati');
INSERT INTO Country(CountryName) VALUES ('North Korea');
INSERT INTO Country(CountryName) VALUES ('South Korea');
INSERT INTO Country(CountryName) VALUES ('Kosovo');
INSERT INTO Country(CountryName) VALUES ('Kuwait');
INSERT INTO Country(CountryName) VALUES ('Kyrgyzstan');
INSERT INTO Country(CountryName) VALUES ('Laos');
INSERT INTO Country(CountryName) VALUES ('Latvia');
INSERT INTO Country(CountryName) VALUES ('Lebanon');
INSERT INTO Country(CountryName) VALUES ('Lesotho');
INSERT INTO Country(CountryName) VALUES ('Liberia');
INSERT INTO Country(CountryName) VALUES ('Libya');
INSERT INTO Country(CountryName) VALUES ('Liechtenstein');
INSERT INTO Country(CountryName) VALUES ('Lithuania');
INSERT INTO Country(CountryName) VALUES ('Luxembourg');
INSERT INTO Country(CountryName) VALUES ('Macau');
INSERT INTO Country(CountryName) VALUES ('Madagascar');
INSERT INTO Country(CountryName) VALUES ('Malawi');
INSERT INTO Country(CountryName) VALUES ('Malaysia');
INSERT INTO Country(CountryName) VALUES ('Maldives');
INSERT INTO Country(CountryName) VALUES ('Mali');
INSERT INTO Country(CountryName) VALUES ('Malta');
INSERT INTO Country(CountryName) VALUES ('Marshall Islands');
INSERT INTO Country(CountryName) VALUES ('Martinique');
INSERT INTO Country(CountryName) VALUES ('Mauritania');
INSERT INTO Country(CountryName) VALUES ('Mauritius');
INSERT INTO Country(CountryName) VALUES ('Mayotte');
INSERT INTO Country(CountryName) VALUES ('Mexico');
INSERT INTO Country(CountryName) VALUES ('Micronesia');
INSERT INTO Country(CountryName) VALUES ('Moldova');
INSERT INTO Country(CountryName) VALUES ('Monaco');
INSERT INTO Country(CountryName) VALUES ('Mongolia');
INSERT INTO Country(CountryName) VALUES ('Montenegro');
INSERT INTO Country(CountryName) VALUES ('Morocco');
INSERT INTO Country(CountryName) VALUES ('Mozambique');
INSERT INTO Country(CountryName) VALUES ('Myanmar (Burma)');
INSERT INTO Country(CountryName) VALUES ('Namibia');
INSERT INTO Country(CountryName) VALUES ('Nauru');
INSERT INTO Country(CountryName) VALUES ('Nepal');
INSERT INTO Country(CountryName) VALUES ('Netherlands');
INSERT INTO Country(CountryName) VALUES ('New Caledonia');
INSERT INTO Country(CountryName) VALUES ('New Zealand');
INSERT INTO Country(CountryName) VALUES ('Nicaragua');
INSERT INTO Country(CountryName) VALUES ('Niger');
INSERT INTO Country(CountryName) VALUES ('Nigeria');
INSERT INTO Country(CountryName) VALUES ('North Macedonia');
INSERT INTO Country(CountryName) VALUES ('Northern Mariana Islands');
INSERT INTO Country(CountryName) VALUES ('Norway');
INSERT INTO Country(CountryName) VALUES ('Oman');
INSERT INTO Country(CountryName) VALUES ('Pakistan');
INSERT INTO Country(CountryName) VALUES ('Palau');
INSERT INTO Country(CountryName) VALUES ('Panama');
INSERT INTO Country(CountryName) VALUES ('Papua New Guinea');
INSERT INTO Country(CountryName) VALUES ('Paraguay');
INSERT INTO Country(CountryName) VALUES ('Peru');
INSERT INTO Country(CountryName) VALUES ('Philippines');
INSERT INTO Country(CountryName) VALUES ('Poland');
INSERT INTO Country(CountryName) VALUES ('Portugal');
INSERT INTO Country(CountryName) VALUES ('Puerto Rico');
INSERT INTO Country(CountryName) VALUES ('Qatar');
INSERT INTO Country(CountryName) VALUES ('Réunion');
INSERT INTO Country(CountryName) VALUES ('Romania');
INSERT INTO Country(CountryName) VALUES ('Russia');
INSERT INTO Country(CountryName) VALUES ('Rwanda');
INSERT INTO Country(CountryName) VALUES ('Saint Kitts and Nevis');
INSERT INTO Country(CountryName) VALUES ('Saint Lucia');
INSERT INTO Country(CountryName) VALUES ('Saint Vincent and the Grenadines');
INSERT INTO Country(CountryName) VALUES ('Samoa');
INSERT INTO Country(CountryName) VALUES ('San Marino');
INSERT INTO Country(CountryName) VALUES ('Sao Tome and Principe');
INSERT INTO Country(CountryName) VALUES ('Saudi Arabia');
INSERT INTO Country(CountryName) VALUES ('Senegal');
INSERT INTO Country(CountryName) VALUES ('Serbia');
INSERT INTO Country(CountryName) VALUES ('Seychelles');
INSERT INTO Country(CountryName) VALUES ('Sierra Leone');
INSERT INTO Country(CountryName) VALUES ('Singapore');
INSERT INTO Country(CountryName) VALUES ('Sint Maarten');
INSERT INTO Country(CountryName) VALUES ('Slovakia');
INSERT INTO Country(CountryName) VALUES ('Slovenia');
INSERT INTO Country(CountryName) VALUES ('Solomon Islands');
INSERT INTO Country(CountryName) VALUES ('Somalia');
INSERT INTO Country(CountryName) VALUES ('South Africa');
INSERT INTO Country(CountryName) VALUES ('Spain');
INSERT INTO Country(CountryName) VALUES ('Sri Lanka');
INSERT INTO Country(CountryName) VALUES ('Sudan');
INSERT INTO Country(CountryName) VALUES ('South Sudan');
INSERT INTO Country(CountryName) VALUES ('Suriname');
INSERT INTO Country(CountryName) VALUES ('Sweden');
INSERT INTO Country(CountryName) VALUES ('Switzerland');
INSERT INTO Country(CountryName) VALUES ('Syria');
INSERT INTO Country(CountryName) VALUES ('Taiwan');
INSERT INTO Country(CountryName) VALUES ('Tajikistan');
INSERT INTO Country(CountryName) VALUES ('Tanzania');
INSERT INTO Country(CountryName) VALUES ('Thailand');
INSERT INTO Country(CountryName) VALUES ('Togo');
INSERT INTO Country(CountryName) VALUES ('Tonga');
INSERT INTO Country(CountryName) VALUES ('Trinidad and Tobago');
INSERT INTO Country(CountryName) VALUES ('Tunisia');
INSERT INTO Country(CountryName) VALUES ('Turkey');
INSERT INTO Country(CountryName) VALUES ('Turkmenistan');
INSERT INTO Country(CountryName) VALUES ('Tuvalu');
INSERT INTO Country(CountryName) VALUES ('Uganda');
INSERT INTO Country(CountryName) VALUES ('Ukraine');
INSERT INTO Country(CountryName) VALUES ('United Arab Emirates');
INSERT INTO Country(CountryName) VALUES ('United Kingdom');
INSERT INTO Country(CountryName) VALUES ('United States');
INSERT INTO Country(CountryName) VALUES ('United States Virgin Islands');
INSERT INTO Country(CountryName) VALUES ('Uruguay');
INSERT INTO Country(CountryName) VALUES ('Uzbekistan');
INSERT INTO Country(CountryName) VALUES ('Vanuatu');
INSERT INTO Country(CountryName) VALUES ('Vatican City');
INSERT INTO Country(CountryName) VALUES ('Venezuela');
INSERT INTO Country(CountryName) VALUES ('Vietnam');
INSERT INTO Country(CountryName) VALUES ('West Bank');
INSERT INTO Country(CountryName) VALUES ('Yemen');
INSERT INTO Country(CountryName) VALUES ('Zambia');
INSERT INTO Country(CountryName) VALUES ('Zimbabwe');
